services:
  - type: web
    name: avion-server-nest-ts
    env: node
    region: oregon
    plan: free
    buildCommand: |
      pnpm install --frozen-lockfile
      pnpm build
    startCommand: pnpm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
